### ISSUE TITLE
Move async Notification methods to Active Jobs

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#1996]
- move asynchronous notification methods to separate Active Jobs
- pass entities `id` instead of an object
- add a check for the entity presence before following up

These methods are suspectible to causing delayed job errors (#1621), so they should be adressed first:

- [x] `send_new_follower_notification` #2030 
- [x] `send_reaction_notification`
- [x] `send_new_comment_notifications`

Other async methods:

- [x] `send_to_followers`
- [x] `send_new_badge_notification` #2474
- [x] `send_welcome_notification` #2485 
- [x] `send_moderation_notification`
- [x] `send_mention_notification` @copasetickid
- [x] `send_tag_adjustment_notification`
- [x] `send_milestone_notification` #2804 
- [x] `remove_all` @cyrillefr
- [x] `remove_each` @cyrillefr 
- [x] `update_notifications` @lightalloy

**Comment by cyrillefr** [comment]
Hello, I'd like to help here. (Maybe with send_welcome_notification).

**Comment by lightalloy** [comment]
@cyrillefr It would be great!  In case of `send_welcome_notification` there's not much code, but I still suggest moving it to a service object and call it from ActiveJob to make testing easier.
You can look at my previous pull requests connected to this issue for reference. Please, feel free to ask any questions while working on this task.

**Comment by rhymes** [comment]
@lightalloy I'll probably help out as well with your direction once #2466 is merged - there are some changes on how active job tests are written that I feel are going to help out in the end. It would be awesome if we'd manage to switch entirely to ActiveJob and not use DelayedJob directly. 🥳

**Comment by lightalloy** [comment]
@rhymes awesome, thanks! Agree on switching to ActiveJob.

**Comment by cyrillefr** [comment]
Hello, I 'd like to help with the Moderation notification.

**Comment by lightalloy** [comment]
I've written a list of actions to move [a method to Active Job](https://github.com/thepracticaldev/dev.to/issues/2497#issuecomment-485396688), it also applies to this ticket.

**Comment by rhymes** [comment]
I think this was closed by mistake because #2485 listed itself as a closing PR

**Comment by cyrillefr** [comment]
Hello, I would like to help with the tag adjustement notification.

**Comment by copasetickid** [comment]
Hi @lightalloy  I'd like to help with the `send_mention_notification`

**Comment by cyrillefr** [comment]
Hello, I'd like to help with `send_milestone_notification`

**Comment by cyrillefr** [comment]
Hello, I'd like to help with the remove_all method

**Comment by lightalloy** [comment]
I'll work on `update_notifications`

**Comment by copasetickid** [comment]
@lightalloy  just confirming I'm working on `send_mention_notification`

**Comment by lightalloy** [comment]
@copasetickid thanks for the confirmation!

**Comment by cyrillefr** [comment]
Hello, I'd like to help with the remove_each method.

**Comment by lightalloy** [comment]
I will work on `send_to_followers` because it seems to cause occasional delayed_job errors.

**Comment by lightalloy** [comment]
Hi, @copasetickid. Are you still working on `send_mention_notification`? If you are still interested and need some help, we can discuss it privately.  E.g. you can [message me](https://dev.to/lightalloy) on dev.to

**Comment by maestromac** [comment]
With all the box checked, I believe this issue is resolved!
