### ISSUE TITLE
Liquid Tag Render Refactor Tracker

### ISSUE THREAD

**Issue by mariocsee** [thepracticaldev/dev.to#2559]
**Describe the bug**
Most/all liquid tags render through markdown parser in the same preparation step articles/comments go through before saving and rendering. Content such as some code, HTML, etc. gets removed in the process, and methods are created to circumvent the parsing (typically using Regex). By using views to render liquid tags, we would not need such methods and methods that help with security can be imported and handled within the xyz_tag.rb.

**Expected behavior**
Changing how liquid tags render -- from going through markdown parser and the same process as how an article/comment is rendered to separately rendering on html.erb view. There are a few open liquid tag related issues that will and may be solved by this refactor. 

**Liquid Tag Tracker**
- [x] dev.to Comment #2554 merged
- [x] dev.to Article/Post #2619 merged
- [x] dev.to User #2621 
- [x] dev.to Tag #2641 merged
- [x] StackBlitz #2664 merged
- [x] dev.to Podcast #2644
- [x] Twitter #2721 
- [x] Runkit #2723 
- [x] Youtube and Vimeo #2728
- [x] Repl.it  
- [x] JS Fiddle
- [x] Codesandbox
- [x] Codepen
- [x] Instagram
- [x] Speakerdeck
- [x] Soundcloud
- [x] Spotify
- [x] Blogcast

**Comment by mariocsee** [comment]
All liquid tags have been refactored. New liquid tags should make sure to render using ActionController with ERB template.
