### ISSUE TITLE
Replace hardcoded meta keywords with the configurable ones

### ISSUE THREAD

**Issue by lightalloy** [thepracticaldev/dev.to#7523]
There are a few types of hardcoded meta keywords that should be configurable:

- [x] `"software development,engineering,rails,javascript,ruby"` (many pages)
- [x] `@article.cached_tag_list + ", software, coding, development, engineering, inclusive, community" ` (`articles/show`)
- [x] `"software development,engineering,<%= @tag %>"` (`tags/meta`)

**Comment by lightalloy** [comment]
To our awesome contributors, please note that this issue will be worked on by a DEV team member and is not up for grabs.

**Comment by lightalloy** [comment]
Closed with #7591
